name: Man10Dice
version: '${project.version}'
main: yusama125718.man10dice.Man10Dice
api-version: 1.19
authors: [ yusama125718 ]

commands:
  mdice:
    description: send a diceroll
    usage: /mdiceでhelpを確認
  mlot:
    description: lottery
    usage: /mlotでhelpを確認

parmissions:
  mdice.op:
    default: op
  mdice.player:
    default: true
  mlot.op:
    default: op
  mlot.player:
    default: true