name: Man10Dice
version: '${project.version}'
main: yusama125718_209282ihcuobust.man10dice.Man10Dice
api-version: 1.17

commands:
  mdice:
    description: send a diceroll
    usage: /<command> [text] [text]

parmissions:
  mdice.op:
    default: op
  mdice.player:
    default: true